# Generated by Django 5.1.2 on 2025-01-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('BERN', 'Bern, Switzerland'), ('BRAS', 'Brasília, Brazil'), ('HK', 'Hong Kong, China'), ('SYD', 'Sydney, Australia'), ('NYC', 'New York, USA')], max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='destinations/')),
                ('landmarks', models.TextField()),
                ('coordinates', models.CharField(max_length=50)),
            ],
        ),
    ]
