# Generated by Django 5.1.2 on 2025-01-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(choices=[('BERN', 'Bern, Switzerland'), ('BRAS', 'Brasília, Brazil'), ('HK', 'Hong Kong, China'), ('SYD', 'Sydney, Australia'), ('NYC', 'New York, USA'), ('ACC', 'Accra, Ghana')], max_length=4),
        ),
    ]
