# Generated by Django 5.1.2 on 2025-01-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_destination_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='destination',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
